### ISSUE TITLE
运行过程中发现缺少数据库

### ISSUE THREAD

**Issue by liuji03** [White-Clouds/bookledingsystem#1]
![屏幕截图 2024-07-01 094302](https://github.com/White-Clouds/booklendingsystem/assets/100551144/33646d9f-10ac-4a11-9720-760da33c2842)

想要试运行一下项目，发现自己创建了缺失的表仍然报错。
请问能否提供一个数据库样板，我自行设置可能对应不上。
非常感谢。

**Comment by liuji03** [comment]
![屏幕截图 2024-07-01 110310](https://github.com/White-Clouds/booklendingsystem/assets/100551144/126e45ec-fce8-49fe-90cd-8a6cdc585ee7)
自行写SQL生成了，准备修改，感谢您的宝贵架构作为参考。

**Comment by White-Clouds** [comment]
django是用模型自动生成数据库的，在`models.py`里面，配置数据库连接后用命令`python manage.py makemigrations`和`python manage.py migrate`生成，django admin还要用`python manage.py createsuperuser`创建超级用户。

**Comment by White-Clouds** [comment]
从头生成要把library目录下的migrations文件夹删除。
